name: Deploy to GitHub Pages
on: 
  push:
    branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GH Pages
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - name: Install Packages
      run: yarn
    - name: Build
      run: yarn build
    - name: 404 Fix
      run: cp ./dist/index.html ./dist/404.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: www.justinforlenza.dev
