name: Deploy

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        name: setup pnpm
        with:
          cache: true

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm run build

      - name: upload files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4